---
site_name: Firefly III documentation
site_description: Documentation for Firefly III
site_author: James Cole
copyright: "&copy; <a href=\"mailto:james@firefly-iii.org\">James Cole</a>,
  licensed under <a
  href=\"https://github.com/firefly-iii/docs/blob/main/license\">Attribution-Sh\
  areAlike 4.0 International</a>."
repo_url: https://github.com/firefly-iii/firefly-iii/
edit_uri: https://github.com/firefly-iii/docs/tree/main/docs/docs
site_url: https://docs.firefly-iii.org/
dev_addr: 10.0.0.15:8000
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#1e6581"
  - git-revision-date
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Tutorials:
      - Home: tutorials/index.md
      - Firefly III:
          - Your finances:
              - My first accounts: tutorials/finances/first-steps.md
              - Create accounts and transactions: tutorials/finances/first-accounts.md
              - Manage a bill: tutorials/finances/bill.md
              - Process a refund: tutorials/finances/refund.md
              - Manage your mortgage: tutorials/finances/mortgage.md
              - Manage multiple currencies: tutorials/finances/currencies.md
          - Data management:
              - Importing data: tutorials/firefly-iii/importing-data.md
              - Exporting data: tutorials/firefly-iii/exporting-data.md
      - Data Importer:
          - Files:
              - Import a basic CSV file: tutorials/data-importer/csv.md
          - Data providers:
              - Import from GoCardless: tutorials/data-importer/gocardless.md
  - How-to guides:
      - Home: how-to/index.md
      - General:
          - How to debug things: how-to/general/debug.md
          - How to report security issues: how-to/general/report-security-issues.md
      - Firefly III:
          - How to install:
              - Using Docker: how-to/firefly-iii/installation/docker.md
              - Using Kubernetes: how-to/firefly-iii/installation/kubernetes.md
              - Using a self-managed server: how-to/firefly-iii/installation/self-managed.md
          - How to upgrade:
              - Using Docker: how-to/firefly-iii/upgrade/docker.md
              - Using Kubernetes: how-to/firefly-iii/upgrade/kubernetes.md
              - Using a self-managed server: how-to/firefly-iii/upgrade/self-managed.md
          - Advanced installation:
              - How to set up notifications: how-to/firefly-iii/advanced/notifications.md
              - How to use different authentication: how-to/firefly-iii/advanced/authentication.md
              - How to make a backup: how-to/firefly-iii/advanced/backup.md
              - How to set up your local language: how-to/firefly-iii/advanced/locales.md
              - How to configure cron jobs: how-to/firefly-iii/advanced/cron.md
          - Your finances:
              - How to manage accounts: how-to/firefly-iii/finances/accounts.md
              - How to manage budgets: how-to/firefly-iii/finances/budgets.md
              - How to organize transactions: how-to/firefly-iii/finances/transactions.md
              - How to track cash: how-to/firefly-iii/finances/cash.md
              - How to use bills: how-to/firefly-iii/finances/bills.md
              - How to reconcile accounts: how-to/firefly-iii/finances/reconcile.md
              - How to manage liabilities: how-to/firefly-iii/finances/liabilities.md
              - How to use recurring transactions: how-to/firefly-iii/finances/recurring.md
              - How to use piggy banks: how-to/firefly-iii/finances/piggy-banks.md
              - How to read reports: how-to/firefly-iii/finances/reports.md
          - More features:
              - Make it multi-user: how-to/firefly-iii/features/multi-user.md
              - How to use rules: how-to/firefly-iii/features/rules.md
              - How to use webhooks: how-to/firefly-iii/features/webhooks.md
              - How to use the search: how-to/firefly-iii/features/search.md
              - How to use currencies: how-to/firefly-iii/features/currencies.md
              - How to use the CLI: how-to/firefly-iii/features/cli.md
              - How to use the API: how-to/firefly-iii/features/api.md
          - Development:
              - Translations: how-to/firefly-iii/development/translations.md
      - Data Importer:
          - How to install:
              - Using Docker: how-to/data-importer/installation/docker.md
              - Using Kubernetes: how-to/data-importer/installation/kubernetes.md
              - Using a self-managed server: how-to/data-importer/installation/self-managed.md
          - How to configure: how-to/data-importer/how-to-configure.md
          - How to upgrade:
              - Using Docker: how-to/data-importer/upgrade/docker.md
              - Using Kubernetes: how-to/data-importer/upgrade/kubernetes.md
              - Using a self-managed server: how-to/data-importer/upgrade/self-managed.md
          - Importing data:
              - How to import CSV or CAMT.053 files: how-to/data-importer/import/csv.md
              - How to automate the import: how-to/data-importer/import/automated.md
              - How to manage JSON: how-to/data-importer/import/json.md
              - How to map data: how-to/data-importer/import/map-data.md
              - How to use Salt Edge: how-to/data-importer/import/salt-edge.md
              - How to use GoCardLess: how-to/data-importer/import/gocardless.md
              - How to import transfers between accounts: how-to/data-importer/import/transfers.md
              - How to handle (missed) duplicates: how-to/data-importer/import/duplicates.md
          - Advanced things:
              - How to import using CLI: how-to/data-importer/advanced/cli.md
              - How to import using POST: how-to/data-importer/advanced/post.md
              - How to set up notifications: how-to/data-importer/advanced/notifications.md
              - How to set a custom import tag: how-to/data-importer/advanced/custom-import-tag.md
  - Reference guides:
      - Home: references/index.md
      - Firefly III:
          - The CLI: references/firefly-iii/cli.md
          - Account types: references/firefly-iii/account-types.md
          - Transaction types: references/firefly-iii/transaction-types.md
          - All search options: references/firefly-iii/search.md
          - All rule triggers: references/firefly-iii/rule-triggers.md
          - All rule actions: references/firefly-iii/rule-actions.md
          - API:
              - The API: references/firefly-iii/api/index.md
              - Special endpoints: references/firefly-iii/api/specials.md
          - Third parties:
              - Third parties that host Firefly III: references/firefly-iii/third-parties/host.md
              - Third-party tools: references/firefly-iii/third-parties/apps.md
          - Full changelog: references/firefly-iii/changelog.md
      - Data Importer:
          - JSON configuration file: references/data-importer/json.md
          - Data field roles: references/data-importer/roles.md
          - Third-party tools: references/data-importer/third-party-tools.md
          - Public installation: references/data-importer/public.md
          - Duplicate detection: references/data-importer/duplicate-detection.md
          - Full changelog: references/data-importer/changelog.md
      - Frequently Asked Questions:
          - Firefly III:
              - General questions: references/faq/firefly-iii/general.md
              - Using and running: references/faq/firefly-iii/using.md
              - Financial management: references/faq/firefly-iii/finances.md
          - Data Importer:
              - General questions: references/faq/data-importer/general.md
              - Common import issues: references/faq/data-importer/import.md
              - Salt Edge and GoCardless: references/faq/data-importer/salt-edge-gocardless.md
          - Installing and running: references/faq/install.md
          - Development: references/faq/development.md
          - Docker: references/faq/docker.md
      - Support: references/support.md
  - Explanation:
      - Home: explanation/index.md
      - Financial concepts:
          - Transactions: explanation/financial-concepts/transactions.md
          - Accounts: explanation/financial-concepts/accounts.md
          - Budgets: explanation/financial-concepts/budgets.md
          - Liabilities: explanation/financial-concepts/liabilities.md
          - Currencies: explanation/financial-concepts/currencies.md
          - Piggy banks: explanation/financial-concepts/piggy-banks.md
          - Bills: explanation/financial-concepts/bills.md
          - Recurring transactions: explanation/financial-concepts/recurring.md
      - Firefly III:
          - About Firefly III:
              - Introduction and features: explanation/firefly-iii/about/introduction.md
              - Screenshots: explanation/firefly-iii/about/screenshots.md
              - Demo website: explanation/firefly-iii/about/demo.md
          - Background information:
              - Personal finances: explanation/firefly-iii/background/personal-finances.md
              - Zero based budgeting: explanation/firefly-iii/background/zero-based-budgeting.md
      - Data Importer:
          - About the Data Importer:
              - Introduction and features: explanation/data-importer/about/introduction.md
              - GoCardless and Salt Edge: explanation/data-importer/about/gocardless-salt-edge.md
          - Separate tool: explanation/data-importer/separate-tool.md
          - Ignored values: explanation/data-importer/ignored-values.md
      - More information:
          - Logo and name: explanation/more-information/logo.md
          - Architecture: explanation/more-information/architecture.md
          - Security: explanation/more-information/security.md
          - License: explanation/more-information/license.md
          - Financial contributions: explanation/more-information/money.md
          - Missing features: explanation/more-information/what-its-not.md
          - (Security) testing: explanation/more-information/bending-and-breaking.md
      - Other tools: explanation/other-tools.md
      - Support: explanation/support.md

extra_css:
  - stylesheets/extra.css
theme:
  font: false
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.path
    - content.action.edit
    - content.code.select
    - content.code.annotate
    - content.code.copy
  palette:
    scheme: fireflyiii
  logo: images/logo.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@ff3
    - icon: fontawesome/brands/github
      link: https://github.com/firefly-iii
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/firefly-iii/firefly-iii
    - icon: fontawesome/solid/globe
      link: https://www.firefly-iii.org/?mtm_campaign=documentation&mtm_kwd=bottom-link
extra:
  analytics:
    provider: custom
    property: custom_property
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            <p>Sorry to hear that :(. Please leave your feedback down here <a href="https://github.com/orgs/firefly-iii/discussions">or on GitHub</a>. Thank you!</p>
            <div id="empty-feedback-form"></div>
